// Code generated by go-ultra-enum; DO NOT EDIT.
package parser

type colorEnum struct {
	Red       colorEle
	LightBlue colorEle
}
type colorEle struct {
	Name        string
	Value       string
	Description string
}

var Color = colorEnum{
	Red:       colorEle{Name: "Red", Value: "RED", Description: ""},
	LightBlue: colorEle{Name: "LightBlue", Value: "LIGHT_BLUE", Description: ""},
}

type statusEnum struct {
	On  statusEle
	Off statusEle
}
type statusEle struct {
	Name        string
	Value       int
	Description string
}

var Status = statusEnum{
	On:  statusEle{Name: "On", Value: 1, Description: ""},
	Off: statusEle{Name: "Off", Value: 0, Description: ""},
}

type sushiEnum struct {
	Maki    sushiEle
	Temaki  sushiEle
	Sashimi sushiEle
}
type sushiEle struct {
	Name        string
	Value       string
	Description string
}

var Sushi = sushiEnum{
	Maki:    sushiEle{Name: "Maki", Value: "MAKI", Description: "Rice and filling wrapped in seaweed"},
	Temaki:  sushiEle{Name: "Temaki", Value: "TEMAKI", Description: "Hand rolled into a cone shape"},
	Sashimi: sushiEle{Name: "Sashimi", Value: "SASHIMI", Description: "Fish or shellfish served alone without rice"},
}
