// Code generated by go-ultra-enum; DO NOT EDIT.
package parser

type colorEnum struct {
	Red       colorEle
	LightBlue colorEle
}
type colorEle struct {
	Name        string
	Value       int
	Description string
}

var Color = colorEnum{
	Red:       colorEle{Name: "Red", Value: 2, Description: ""},
	LightBlue: colorEle{Name: "LightBlue", Value: 1, Description: ""},
}

type geoEnum struct {
	Lat geoEle
	Lon geoEle
}
type geoEle struct {
	Name        string
	Value       int64
	Description string
}

var Geo = geoEnum{
	Lat: geoEle{Name: "Lat", Value: 2, Description: ""},
	Lon: geoEle{Name: "Lon", Value: 1, Description: ""},
}

type statusEnum struct {
	On  statusEle
	Off statusEle
}
type statusEle struct {
	Name        string
	Value       bool
	Description string
}

var Status = statusEnum{
	On:  statusEle{Name: "On", Value: true, Description: ""},
	Off: statusEle{Name: "Off", Value: false, Description: ""},
}

type sushiEnum struct {
	Maki    sushiEle
	Temaki  sushiEle
	Sashimi sushiEle
}
type sushiEle struct {
	Name        string
	Value       string
	Description string
}

var Sushi = sushiEnum{
	Maki:    sushiEle{Name: "Maki", Value: "MAKI", Description: "Rice and filling wrapped in seaweed"},
	Temaki:  sushiEle{Name: "Temaki", Value: "TEMAKI", Description: "Hand rolled into a cone shape"},
	Sashimi: sushiEle{Name: "Sashimi", Value: "SASHIMI", Description: "Fish or shellfish served alone without rice"},
}
