// Code generated by go-ultra-enum; DO NOT EDIT.
package parser

import (
	"encoding/json"
	"fmt"
)

type colorEnum struct {
	Red   ColorEle
	Blue  ColorEle
	Grenn ColorEle
}

func (x *colorEnum) Names() []string {
	return []string{
		"Red",
		"Blue",
		"Grenn",
	}
}
func (x *colorEnum) Values() []int {
	return []int{
		1,
		2,
		3,
	}
}
func (x *colorEnum) UnMarshalName(name string) (*ColorEle, error) {
	if val, ok := colorEnumNameMap[name]; ok {
		return val, nil
	}
	return nil, fmt.Errorf("%s does not belong to names", name)
}
func (x *colorEnum) UnMarshalValue(value int) (*ColorEle, error) {
	if val, ok := colorEnumValueMap[value]; ok {
		return val, nil
	}
	return nil, fmt.Errorf("%v does not belong to values", value)
}

type ColorEle struct {
	Name        string
	Value       int
	Description string
}

func (x *ColorEle) MarshalJson() ([]byte, error) {
	return json.Marshal(x)
}

var (
	Color = colorEnum{
		Red:   ColorEle{Name: "Red", Value: 1, Description: ""},
		Blue:  ColorEle{Name: "Blue", Value: 2, Description: ""},
		Grenn: ColorEle{Name: "Grenn", Value: 3, Description: ""},
	}
	colorEnumNameMap = map[string]*ColorEle{
		"Red":   &Color.Red,
		"Blue":  &Color.Blue,
		"Grenn": &Color.Grenn,
	}
	colorEnumValueMap = map[int]*ColorEle{
		1: &Color.Red,
		2: &Color.Blue,
		3: &Color.Grenn,
	}
)

type countryEnum struct {
	China    CountryEle
	America  CountryEle
	Sinapore CountryEle
}

func (x *countryEnum) Names() []string {
	return []string{
		"China",
		"America",
		"Sinapore",
	}
}
func (x *countryEnum) Values() []int64 {
	return []int64{
		1,
		2,
		3,
	}
}
func (x *countryEnum) UnMarshalName(name string) (*CountryEle, error) {
	if val, ok := countryEnumNameMap[name]; ok {
		return val, nil
	}
	return nil, fmt.Errorf("%s does not belong to names", name)
}
func (x *countryEnum) UnMarshalValue(value int64) (*CountryEle, error) {
	if val, ok := countryEnumValueMap[value]; ok {
		return val, nil
	}
	return nil, fmt.Errorf("%v does not belong to values", value)
}

type CountryEle struct {
	Name        string
	Value       int64
	Description string
}

func (x *CountryEle) MarshalJson() ([]byte, error) {
	return json.Marshal(x)
}

var (
	Country = countryEnum{
		China:    CountryEle{Name: "China", Value: 1, Description: ""},
		America:  CountryEle{Name: "America", Value: 2, Description: ""},
		Sinapore: CountryEle{Name: "Sinapore", Value: 3, Description: ""},
	}
	countryEnumNameMap = map[string]*CountryEle{
		"China":    &Country.China,
		"America":  &Country.America,
		"Sinapore": &Country.Sinapore,
	}
	countryEnumValueMap = map[int64]*CountryEle{
		1: &Country.China,
		2: &Country.America,
		3: &Country.Sinapore,
	}
)

type statusEnum struct {
	On  StatusEle
	Off StatusEle
}

func (x *statusEnum) Names() []string {
	return []string{
		"On",
		"Off",
	}
}
func (x *statusEnum) Values() []bool {
	return []bool{
		true,
		false,
	}
}
func (x *statusEnum) UnMarshalName(name string) (*StatusEle, error) {
	if val, ok := statusEnumNameMap[name]; ok {
		return val, nil
	}
	return nil, fmt.Errorf("%s does not belong to names", name)
}
func (x *statusEnum) UnMarshalValue(value bool) (*StatusEle, error) {
	if val, ok := statusEnumValueMap[value]; ok {
		return val, nil
	}
	return nil, fmt.Errorf("%v does not belong to values", value)
}

type StatusEle struct {
	Name        string
	Value       bool
	Description string
}

func (x *StatusEle) MarshalJson() ([]byte, error) {
	return json.Marshal(x)
}

var (
	Status = statusEnum{
		On:  StatusEle{Name: "On", Value: true, Description: ""},
		Off: StatusEle{Name: "Off", Value: false, Description: ""},
	}
	statusEnumNameMap = map[string]*StatusEle{
		"On":  &Status.On,
		"Off": &Status.Off,
	}
	statusEnumValueMap = map[bool]*StatusEle{
		true:  &Status.On,
		false: &Status.Off,
	}
)

type sushiEnum struct {
	Maki    SushiEle
	Temaki  SushiEle
	Sashimi SushiEle
}

func (x *sushiEnum) Names() []string {
	return []string{
		"Maki",
		"Temaki",
		"Sashimi",
	}
}
func (x *sushiEnum) Values() []string {
	return []string{
		"MAKI",
		"TEMAKI",
		"SASHIMI",
	}
}
func (x *sushiEnum) UnMarshalName(name string) (*SushiEle, error) {
	if val, ok := sushiEnumNameMap[name]; ok {
		return val, nil
	}
	return nil, fmt.Errorf("%s does not belong to names", name)
}
func (x *sushiEnum) UnMarshalValue(value string) (*SushiEle, error) {
	if val, ok := sushiEnumValueMap[value]; ok {
		return val, nil
	}
	return nil, fmt.Errorf("%v does not belong to values", value)
}

type SushiEle struct {
	Name        string
	Value       string
	Description string
}

func (x *SushiEle) MarshalJson() ([]byte, error) {
	return json.Marshal(x)
}

var (
	Sushi = sushiEnum{
		Maki:    SushiEle{Name: "Maki", Value: "MAKI", Description: "Rice and filling wrapped in seaweed"},
		Temaki:  SushiEle{Name: "Temaki", Value: "TEMAKI", Description: "Hand rolled into a cone shape"},
		Sashimi: SushiEle{Name: "Sashimi", Value: "SASHIMI", Description: "Fish or shellfish served alone without rice"},
	}
	sushiEnumNameMap = map[string]*SushiEle{
		"Maki":    &Sushi.Maki,
		"Temaki":  &Sushi.Temaki,
		"Sashimi": &Sushi.Sashimi,
	}
	sushiEnumValueMap = map[string]*SushiEle{
		"MAKI":    &Sushi.Maki,
		"TEMAKI":  &Sushi.Temaki,
		"SASHIMI": &Sushi.Sashimi,
	}
)
