// Code generated by go-ultra-enum; DO NOT EDIT.
package parser

type colorEnum struct {
	Red       colorEle
	LightBlue colorEle
}
type colorEle struct {
	Name        string
	Value       int
	Description string
}

func (n *colorEnum) Names() []string {
	return []string{
		"Red",
		"LightBlue",
	}
}
func (n *colorEnum) Values() []int {
	return []int{
		2,
		1,
	}
}

var Color = colorEnum{
	Red:       colorEle{Name: "Red", Value: 2, Description: ""},
	LightBlue: colorEle{Name: "LightBlue", Value: 1, Description: ""},
}

type geoEnum struct {
	Lat geoEle
	Lon geoEle
}
type geoEle struct {
	Name        string
	Value       int64
	Description string
}

func (n *geoEnum) Names() []string {
	return []string{
		"Lat",
		"Lon",
	}
}
func (n *geoEnum) Values() []int64 {
	return []int64{
		2,
		1,
	}
}

var Geo = geoEnum{
	Lat: geoEle{Name: "Lat", Value: 2, Description: ""},
	Lon: geoEle{Name: "Lon", Value: 1, Description: ""},
}

type statusEnum struct {
	On  statusEle
	Off statusEle
}
type statusEle struct {
	Name        string
	Value       bool
	Description string
}

func (n *statusEnum) Names() []string {
	return []string{
		"On",
		"Off",
	}
}
func (n *statusEnum) Values() []bool {
	return []bool{
		true,
		false,
	}
}

var Status = statusEnum{
	On:  statusEle{Name: "On", Value: true, Description: ""},
	Off: statusEle{Name: "Off", Value: false, Description: ""},
}

type sushiEnum struct {
	Maki    sushiEle
	Temaki  sushiEle
	Sashimi sushiEle
}
type sushiEle struct {
	Name        string
	Value       string
	Description string
}

func (n *sushiEnum) Names() []string {
	return []string{
		"Maki",
		"Temaki",
		"Sashimi",
	}
}
func (n *sushiEnum) Values() []string {
	return []string{
		"MAKI",
		"TEMAKI",
		"SASHIMI",
	}
}

var Sushi = sushiEnum{
	Maki:    sushiEle{Name: "Maki", Value: "MAKI", Description: "Rice and filling wrapped in seaweed"},
	Temaki:  sushiEle{Name: "Temaki", Value: "TEMAKI", Description: "Hand rolled into a cone shape"},
	Sashimi: sushiEle{Name: "Sashimi", Value: "SASHIMI", Description: "Fish or shellfish served alone without rice"},
}
