package parser

const Header = `// Code generated by go-struct-enum; DO NOT EDIT.
	package {{.Name}}
`
const Tpl = `type {{.NewName | LcFirst}}Enum struct{
{{ range $e := .Elements}}
{{$e.Name}} {{$.NewName | LcFirst}}Ele{{ end}}
}
type {{.NewName | LcFirst}}Ele struct {
    Name string
    Value {{.Tpe}}
    Description string
}

var {{.NewName}} = {{.NewName | LcFirst }}Enum{
{{- range $e := .Elements}}
    {{.Name}} : {{$.NewName | LcFirst}}Ele{Name: "{{.Name}}", Value: {{if eq .Tpe "string"}}"{{.Value}}"{{else}}{{.Value}}{{end}}, Description: "{{.Description}}"},
{{- end}}
}
`
