package parser

const Header = `// Code generated by go-ultra-enum; DO NOT EDIT.
	package {{.Name}}
`
const Tpl = `type {{.NewName | LcFirst}}Enum struct{
{{ range $e := .Elements}}
{{$e.Name}} {{$.NewName | LcFirst}}Ele{{ end}}
}
type {{.NewName | LcFirst}}Ele struct {
    Name string
    Value {{.Tpe}}
    Description string
}
func (n *{{.NewName | LcFirst}}Enum)Names() []string{
    return []string{
        {{- range $e := .Elements}}
            "{{.Name}}",
        {{- end}}
    }
}
func (n *{{.NewName | LcFirst}}Enum)Values() []{{.Tpe}}{
    return []{{.Tpe}}{
        {{- range $e := .Elements}}
            {{if eq .Tpe "string"}}"{{.Value}}"{{else}}{{.Value}}{{end}},
        {{- end}}
    }
}

var {{.NewName}} = {{.NewName | LcFirst }}Enum{
{{- range $e := .Elements}}
    {{.Name}} : {{$.NewName | LcFirst}}Ele{Name: "{{.Name}}", Value: {{if eq .Tpe "string"}}"{{.Value}}"{{else}}{{.Value}}{{end}}, Description: "{{.Description}}"},
{{- end}}
}
`
